version: '3.8'

services:
  link-tracker:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
    volumes:
      - trackerr_data:/app/data
    restart: unless-stopped

volumes:
  trackerr_data:
    driver: local
